### ISSUE TITLE
Jam Build Failure - Incorrect Index accessed when array size is 3

### ISSUE THREAD

**Issue by saurabheights** [tokenrove/blur-detection#3]
In [tong-li-zhang-zhang.h](https://github.com/tokenrove/blur-detection/blob/master/tong-li-zhang-zhang.h) we have LEVELS defined as 3.

However, in [tong-li-zhang-zhang.c](https://github.com/tokenrove/blur-detection/blob/master/tong-li-zhang-zhang.c#L40), we are accessing p[3]. This causes JAM build failure.

**Comment by tokenrove** [comment]
Worse than that, it probably corrupts the stack in some cases.  I guess it never did before, because in optimized builds, the three values in use all go on the x87 stack, or the xmm registers in the case of x86-64.  In any case, this should be fixed on `master`.  Note that this code is unmaintained and I don't guarantee further updates.  It's pretty old and needs some love.

**Comment by saurabheights** [comment]
Shouldn't we just change the size of array p to float p[LEVELS+1]. It will prevent any stack corruption as well as JAM build failure.

**Comment by tokenrove** [comment]
No, see commit 64aac0864671137fed2d82bd111214725b4f1975 .  `p[0]` was previously unused.  Anyway, if you look at the disassembly, at least for any modern gcc, you can see why it didn't cause stack corruption, as I speculated earlier:

```asm
  72:   f3 0f 10 0c 82          movss  (%rdx,%rax,4),%xmm1
  77:   f3 42 0f 11 4c 0c f0    movss  %xmm1,-0x10(%rsp,%r9,1)
  7e:   83 c1 01                add    $0x1,%ecx
  81:   49 83 c1 04             add    $0x4,%r9
  85:   49 83 f9 0c             cmp    $0xc,%r9
  89:   75 b0                   jne    3b <detect_blur+0x3b>
  8b:   f3 0f 10 4c 24 f0       movss  -0x10(%rsp),%xmm1
  91:   0f 2e c8                ucomiss %xmm0,%xmm1
  94:   77 16                   ja     ac <detect_blur+0xac>
  96:   f3 0f 10 54 24 f4       movss  -0xc(%rsp),%xmm2
  9c:   0f 2e d0                ucomiss %xmm0,%xmm2
  9f:   77 0b                   ja     ac <detect_blur+0xac>
  a1:   f3 0f 10 54 24 f8       movss  -0x8(%rsp),%xmm2
  a7:   0f 2e d0                ucomiss %xmm0,%xmm2
  aa:   76 41                   jbe    ed <detect_blur+0xed>
  ac:   41 83 c4 01             add    $0x1,%r12d
  b0:   f3 0f 10 54 24 f4       movss  -0xc(%rsp),%xmm2
  b6:   0f 2e ca                ucomiss %xmm2,%xmm1
  b9:   76 0e                   jbe    c9 <detect_blur+0xc9>
  bb:   0f 2e 54 24 f8          ucomiss -0x8(%rsp),%xmm2
  c0:   76 07                   jbe    c9 <detect_blur+0xc9>
  c2:   83 44 24 dc 01          addl   $0x1,-0x24(%rsp)
  c7:   eb 24                   jmp    ed <detect_blur+0xed>
  c9:   0f 2e d1                ucomiss %xmm1,%xmm2
  cc:   76 1f                   jbe    ed <detect_blur+0xed>
  ce:   f3 0f 10 5c 24 f8       movss  -0x8(%rsp),%xmm3
  d4:   0f 2e da                ucomiss %xmm2,%xmm3
  d7:   77 05                   ja     de <detect_blur+0xde>
  d9:   0f 2e d3                ucomiss %xmm3,%xmm2
  dc:   76 0f                   jbe    ed <detect_blur+0xed>
  de:   41 83 c6 01             add    $0x1,%r14d
  e2:   41 8d 45 01             lea    0x1(%r13),%eax
  e6:   0f 2e c1                ucomiss %xmm1,%xmm0
  e9:   44 0f 47 e8             cmova  %eax,%r13d
```

**Comment by se7en007** [comment]
First of all, thank you. I never noticed that you had fixed it 2 days ago. 

Regarding xmm registers(sorry, I am not so good with assembly), I think the use of four registers(xmm0 - xmm3) enabled the code to be optimized (no i-1 computation in the inner most loop).
