### ISSUE TITLE
Sky Ratio being int type is never used

### ISSUE THREAD

**Issue by saurabheights** [tokenrove/blur-detection#4]
Hi Tokenrove,
 Hope you are doing well. I noticed that sky_ratio being an int will always result in getting initialized to 0.

Here we compute sky_histogram which is always less than n. Thus sky_ratio is initiaized to value between 0 and 1, which gets cast to 0.
https://github.com/tokenrove/blur-detection/blob/master/lim-yen-wu.c#L315

**Comment by tokenrove** [comment]
Good catch!  Further evidence that this project needs tests.  Although the fix is trivial, I'd prefer to put in a test that verifies that different values of `sky_threshold` have an effect.  Leaving this issue open until I have the chance to fix #2.

**Comment by saurabheights** [comment]
That's good. I wanted to ask one question. Do you have some google group? I have partially imported your code to C++ utilizing strategy pattern for different Local Blur Detection techniques.  However, there will be few topics I would require to discuss and google group will be good for that. Thank you.
